#### linear regression multiple variables

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
df=pd.read_csv("homeprices.csv")

In [8]:
df    # there is null so we have to replase that null

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
import math
df.bedrooms.median()

4.0

In [17]:
df["bedrooms"]=df["bedrooms"].fillna(df["bedrooms"].median())

In [18]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [20]:
x=df[["area","bedrooms","age"]]

In [24]:
y=df[["price"]]

In [32]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [55]:
model.fit(x,y)    # you can use x_train ,y_tain

LinearRegression()

In [56]:
model.predict([[3000,3,40]])

C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[498408.25158031]])

In [57]:
model.coef_               # age negative(output) because age increase bulding rate decrease

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [58]:
model.intercept_

array([221323.0018654])

In [59]:
## how did it predicted

In [60]:
112.06244194*3000+23388.88007794*3+-3231.71790863*10+221323.0018654   # y=mx+c

595359.7888329199

In [61]:
model.score(x_test,y_test)

0.987726051920626